/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lastools_LASHeader */

#ifndef _Included_org_lastools_LASHeader
#define _Included_org_lastools_LASHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lastools_LASHeader
 * Method:    check
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lastools_LASHeader_check
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASHeader
 * Method:    isCompressed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lastools_LASHeader_isCompressed
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASHeader
 * Method:    isLonLat
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lastools_LASHeader_isLonLat
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASHeader
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lastools_LASHeader_dealloc
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
