/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lastools_LASlibJNI */

#ifndef _Included_org_lastools_LASlibJNI
#define _Included_org_lastools_LASlibJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lastools_LASlibJNI
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lastools_LASlibJNI_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
