/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lastools_LASReader */

#ifndef _Included_org_lastools_LASReader
#define _Included_org_lastools_LASReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lastools_LASReader
 * Method:    alloc
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_lastools_LASReader_alloc
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_lastools_LASReader
 * Method:    dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lastools_LASReader_dealloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_lastools_LASReader
 * Method:    getHeader
 * Signature: ()Lorg/lastools/LASHeader;
 */
JNIEXPORT jobject JNICALL Java_org_lastools_LASReader_getHeader
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    readPoint
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lastools_LASReader_readPoint
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getPoint
 * Signature: ()Lorg/lastools/LASPoint;
 */
JNIEXPORT jobject JNICALL Java_org_lastools_LASReader_getPoint
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getMinX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getMinX
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getMinY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getMinY
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getMinZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getMinZ
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getMaxX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getMaxX
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getMaxY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getMaxY
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getMaxZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getMaxZ
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getX
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getY
  (JNIEnv *, jobject);

/*
 * Class:     org_lastools_LASReader
 * Method:    getZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_lastools_LASReader_getZ
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
